### ISSUE TITLE
Allow Oauth2 authentication with Portal IWA and Federated Server.

### ISSUE THREAD

**Issue by hmelendez** [Esri/resource-proxy#310]
I have a Portal installation that is secured using Integrated Windows Authentication. I'm trying to use this proxy to access my secure Server federated services using Oauth2, Client ID and Secret in an app. The problem is that when the proxy tries to access the Oauth2 endpoint the WebAdaptor doesn't allow it since the proxy has no windows credentials to pass through. I tried using the **oauth2Endpoint** pointing to the internal portal:<**port**>/arcgis/sharing/oauth2/.and this effectively bypasses the WebAdaptor and generates a token but the token that is generated is invalid i'm guessing because the returnURI is incorrect as well.

You might wonder why not use Username Password Domain. The reason is that windows account expire and passwords have to bee reset, also I do not want to loss a Name User from my portal just to handle my apps authentications.

I already check with Esri Technical support and the portal supports this scenario but the proxy can't handle it at the moment.

Any help would be mush aprecieted.

**Comment by jgravois** [comment]
you might check out the untested pull request [here](https://github.com/Esri/resource-proxy/pull/309) which introduces support for allowing users to impersonate an IIS Application Pool Identity instead.

**Comment by hmelendez** [comment]
I get this error with the recomended change:

 

The remote server returned an error: (401) Unauthorized.

   at System.Net.HttpWebRequest.GetResponse()

   at proxy.doHTTPRequest(String uri, Byte[] bytes, String method, String referer, String contentType, NetworkCredential credentials) in c:\inetpub\wwwroot\proxy\proxy.ashx:line 478

   at proxy.doHTTPRequest(String uri, String method, NetworkCredential credentials) in c:\inetpub\wwwroot\proxy\proxy.ashx:line 453

   at proxy.getNewTokenIfCredentialsAreSpecified(ServerUrl su, String reqUrl) in c:\inetpub\wwwroot\proxy\proxy.ashx:line 506

   at proxy.ProcessRequest(HttpContext context) in c:\inetpub\wwwroot\proxy\proxy.ashx:line 260

   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()

   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

 

 

Héctor R. Meléndez Alvarado
Arquitecto de Soluciones


Geographic Mapping Technologies, Corp
tel: (787) 250-8182 / (787) 250-8185
hmelendez@gmtgis.com

**Comment by hmelendez** [comment]
I was missing the new parameter **useAppPoolIdentity="true"**. After adding the parameter I'm able to pass trhough the Webadaptor but I don't get a token. I get this error: {"error":{"code":499,"message":"Token Required","details":[]}}

**Comment by esoekianto** [comment]
I think this is the situation where you need to use IWA workflow if you are using the proxy, since the server/portal is federated and secured with windows auth enabled in IIS , you wont be able to make any request to this server/portal without IWA (username/password/domain) credential object because it will throw back the 401 unauthorized from IIS.

and we know that this workflow in proxy works, it is just that the IWA password needs to be reset-ed frequently.

**Comment by esoekianto** [comment]
@hmelendez I have created and helped other user with your similar situation, where we created custom proxy page that will carry both IWA credentials and OAuth2. But still in this case you would still need to update the password to IWA account frequently in proxy.config.

**Comment by bsvensson** [comment]
Closing due to inactivity...
