### ISSUE TITLE
Java6 - Etat HTTP 500 - connect timed out

### ISSUE THREAD

**Issue by mdelsinne** [Esri/resource-proxy#333]
Hi,

I try to use a JSP proxy page with my tomcat6. The ping is Ok. I can access to my ArcGIS server locally through the proxy page, it works well. But I can not enter a REST web page arcgis server (eg http://services.arcgisonline.com/ArcGIS/rest/services/?f=pjson ).

Etat HTTP 500 - connect timed out

GRAVE: A fatal proxy error occurred.
java.net.SocketTimeoutException: connect timed out
      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
      at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)
      at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)
      at java.security.AccessController.doPrivileged(Native Method)
      at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)
      at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)
      at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
      at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
      at org.apache.jsp.proxy_jsp.fetchAndPassBackToClient(proxy_jsp.java:170)
      at org.apache.jsp.proxy_jsp._jspService(proxy_jsp.java:1185)
      at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
      at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:388)
      at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
      at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
      at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
      at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
      at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:311)
      at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
      at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
      at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
      at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
      at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
      at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
      at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
      at java.net.Socket.connect(Socket.java:589)
      at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
      at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
      at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
      at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
      at sun.net.www.http.HttpClient.New(HttpClient.java:308)
      at sun.net.www.http.HttpClient.New(HttpClient.java:326)
      at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
      at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
      at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
      at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
      at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
      at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
      at sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:2965)
      at org.apache.jsp.proxy_jsp.fetchAndPassBackToClient(proxy_jsp.java:147)
      ... 22 more

Thank you for help,

**Comment by mdelsinne** [comment]
I found , you must configure the proxy system to use with tomcat6.

So I added the following lines in proxy.jsp: (before the connection opening)
// Set Proxy system 
System.setProperty("http.proxyHost", "ip_host");
System.setProperty("http.proxyPort", "port_number");

if the proxy requiere authentication, then add also:
System.setProperty("http.proxyUser", "user");
System.setProperty("http.proxyPassword", "password");

Bye
