### ISSUE TITLE
Java Proxy: "Couldn't get lock for proxy_log.log"

### ISSUE THREAD

**Issue by gavinr** [Esri/resource-proxy#353]
I'm attempting to capture the logs in the Java Resource proxy. My `proxy.config`:

```
<?xml version="1.0" encoding="utf-8" ?>
<ProxyConfig allowedReferers="*"
logFile="proxy_log.log"
logLevel="FINE"
mustMatch="true">
<serverUrls>
<serverUrl url="http://...:6080"
matchAll="true"/>
<serverUrl url="http://...:6080"
matchAll="true"/>.
<serverUrl url="http://services.arcgisonline.com"
matchAll="true"/>
<serverUrl url="http://server.arcgisonline.com"
matchAll="true"/>
</serverUrls>
</ProxyConfig>
```

I'm getting an error in `/var/log/tomcat7/catalina.out`:

```
Error writing to log:
2016-04-13 21:01:37 Creating request for: http://...:6080/arcgis/rest/services/PROD/OPERATIONAL/FeatureServer/1/query?f=json&where=1........4.
java.io.IOException: Couldn't get lock for proxy_log.log
at java.util.logging.FileHandler.openFiles(FileHandler.java:389)
at java.util.logging.FileHandler.<init>(FileHandler.java:287)
at org.apache.jsp.proxy.proxy_jsp._log(proxy_jsp.java:562)
at org.apache.jsp.proxy.proxy_jsp._log(proxy_jsp.java:606)
at org.apache.jsp.proxy.proxy_jsp._jspService(proxy_jsp.java:1053)
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
```

Here is my current directory structure. Relative to where do I need to place `proxy_log.log` for this to work? Or is it maybe a folder permissions issue? Thanks!

```
.
├── index.html
├── META-INF
│   └── context.xml
├── proxy
│   └── proxy.jsp
├── proxy_log.log
└── WEB-INF
└── classes
└── proxy.config
```

**Comment by esoekianto** [comment]
@gavinr yes, sounds like file permission issue

**Comment by gavinr** [comment]
@esoekianto I gave the files `chmod 777 proxy_log.log`, restarted tomcat, and still getting same issue, so I don't think that's it ... do you know if the location relative to my `proxy.jsp` is correct? I've also tried these to no avail:

* `proxy/proxy_log.log` (sibling to `proxy.jsp`)
* `WEB-INF/proxy_log.log`

**Comment by kelylah** [comment]
I've the same issue. Any clue what can be wrong?
