### ISSUE TITLE
Getting an error from Portal 10.61

### ISSUE THREAD

**Issue by SaiAnandPeketi** [Esri/resource-proxy#507]
Hi I'm getting an error 400 from proxy.ashx using portal for arcgis 10.61. "{\"error\":{\"code\":400,\"message\":\"Unable to generate token.\",\"details\":[\"Invalid username or password.\"]}}" Same code works for Portal 10.41. I tested the token genrartion from postman. it's working fine, but whenever tried to proxy.ashx?<Rest Service>

**Comment by guus-stedin** [comment]
Hiya... We're having a similar issue. Changing the instance recycle timer to say... 1000 requests resolves SOME of it, however it's not desired, and the application is still crashing... looking at event viewer, Windows is logging a tonne of these. If it's true that 304 messages are crashing the proxy, that'd be silly as 304's are perfectly harmless... Could you check if you have a similar issue?:

```
Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 2/26/2019 11:05:05 AM 
Event time (UTC): 2/26/2019 10:05:05 AM 
Event ID: 7c99c25c225f4621859cb959436199b2 
Event sequence: 455 
Event occurrence: 1 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/1/ROOT/ApexProxy-1-131956490614931256 
    Trust level: Full 
    Application Virtual Path: /ApexProxy 
    Application Path: C:\bla\ApexProxy\ 
    Machine name: notgonnatellya 
 
Process information: 
    Process ID: 109616 
    Process name: w3wp.exe 
    Account name: SG\arcgis 
 
Exception information: 
    Exception type: WebException 
    Exception message: The remote server returned an error: (304) Not Modified.
   at System.Net.HttpWebRequest.GetResponse()
   at proxy.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

 
 
Request information: 
    Request URL: https://notgonnatellya:443/apexproxy/proxy.ashx?https://itsaportal/portal/sharing/rest/content/items/582ed3bda2c94d6dacabfdb5316f2db2/data?f=json 
    Request path: /apexproxy/proxy.ashx 
    User host address: 10.213.233.175 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: SG\arcgis 
 
Thread information: 
    Thread ID: 19 
    Thread account name: SG\arcgis 
    Is impersonating: False 
    Stack trace:    at System.Net.HttpWebRequest.GetResponse()
   at proxy.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
 
 
Custom event details: 
```
